### ISSUE TITLE
Windows Install Error: TypeError: str expected, not bytes

### ISSUE THREAD

**Issue by sshaw** [cask/cask#285]
Similar to #140.

Here's the output:

```
C:\Users\sshaw> curl -kfsSL https://raw.githubusercontent.com/cask/cask/master/go | python
Cloning into 'C:\Users\sshaw\.cask'...
remote: Counting objects: 3235, done.
remote: Compressing objects: 100% (5/5), done.
rRemote: Total 3235 (delta 0), reused 0 (delta 0), pack-reused 3230eceiving objects: 100% (3235/3235
Receiving objects: 100% (3235/3235), 1001.62 KiB | 1.29 MiB/s, done.

Resolving deltas: 100% (1812/1812), done.
Checking connectivity... done.
Traceback (most recent call last):
  File "C:\Users\sshaw\.cask\bin\cask", line 347, in <module>
    main()
  File "C:\Users\sshaw\.cask\bin\cask", line 330, in main
    exec_cask(sys.argv[1:])
  File "C:\Users\sshaw\.cask\bin\cask", line 292, in exec_cask
    emacs = get_cask_emacs()
  File "C:\Users\sshaw\.cask\bin\cask", line 257, in get_cask_emacs
    emacs = ENVB.get(b'EMACS') if b'INSIDE_EMACS' not in ENVB else None
  File "C:\Python34\lib\_collections_abc.py", line 428, in __contains__
    self[key]
  File "C:\Python34\lib\os.py", line 630, in __getitem__
    value = self._data[self.encodekey(key)]
  File "C:\Python34\lib\os.py", line 697, in encodekey
    return encode(key).upper()
  File "C:\Python34\lib\os.py", line 692, in check_str
    raise TypeError("str expected, not %s" % type(value).__name__)
TypeError: str expected, not bytes
←[31mCask could not be bootstrapped. Try again later, or report an issue at https://github.com/cask/
cask/issues←[0m
```

Also note that if I run `curl` + `go` again:

```
C:\Users\sshaw> curl -kfsSL https://raw.githubusercontent.com/cask/cask/master/go | python
←[31mDirectory C:\Users\sshaw\.cask exists. Is Cask already installed?←[0m
```

```
C:\Users\sshaw>python --version
Python 3.4.3
```

Let me know if you need more details

**Comment by melihovv** [comment]
I have the same error. Pls help anybody

**Comment by sshaw** [comment]
@melihovv the workaround is to run it with Python 2.
