### ISSUE TITLE
unable to install

### ISSUE THREAD

**Issue by samuelzhou-dev** [cask/cask#448]
![image](https://user-images.githubusercontent.com/43336428/46245453-770ae380-c420-11e8-81b8-772f0f3e8081.png)

**Comment by Fuco1** [comment]
What OS, what version of python.  Give us more info.

**Comment by lordnik22** [comment]
Got the same error-msg on Windows 10 with Python 3.5.

Stack-Trace (runned in GNU bash 4.4.12):
```
$ curl -fsSL https://raw.githubusercontent.com/cask/cask/master/go | python
Cloning into 'E:\cygwin64\home\Lordnik\.cask'...
remote: Enumerating objects: 1, done.
remote: Counting objects: 100% (1/1), done.
remote: Total 3653 (delta 0), reused 0 (delta 0), pack-reused 3652R
Receiving objects: 100% (3653/3653), 1.17 MiB | 1.76 MiB/s, done.
Resolving deltas: 100% (2067/2067), done.
Checking connectivity... done.
Traceback (most recent call last):
  File "E:\cygwin64\home\Lordnik\.cask\bin\cask", line 425, in <module>
    main()
  File "E:\cygwin64\home\Lordnik\.cask\bin\cask", line 387, in main
    if ENVB.get(b'TRAVIS', b'') == b'true':
  File "E:\Python35\lib\_collections_abc.py", line 595, in get
    return self[key]
  File "E:\Python35\lib\os.py", line 678, in __getitem__
    value = self._data[self.encodekey(key)]
  File "E:\Python35\lib\os.py", line 745, in encodekey
    return encode(key).upper()
  File "E:\Python35\lib\os.py", line 740, in check_str
    raise TypeError("str expected, not %s" % type(value).__name__)
TypeError: str expected, not bytes
[31mCask could not be bootstrapped. Try again later, or report an issue at https://github.com/cask/cask/issues[0m
```

**Comment by bradyt** [comment]
This is a duplicate to https://github.com/cask/cask/issues/285.

**Comment by mikeo85** [comment]
I'm getting the same TypeError when trying to bootstrap. I'm running Windows 10, Python 3.6.5, from the standard command prompt. 

Any updates? Thanks!

```
C:\Users\mikeo85>curl -fsSL https://raw.githubusercontent.com/cask/cask/master/go | python
Cloning into 'C:\Users\mikeo85\.cask'...
remote: Enumerating objects: 3653, done.
remote: Total 3653 (delta 0), reused 0 (delta 0), pack-reused 3653
Receiving objects: 100% (3653/3653), 1.17 MiB | 2.81 MiB/s, done.
Resolving deltas: 100% (2067/2067), done.
Traceback (most recent call last):
  File "C:\Users\mikeo85\.cask\bin\cask", line 425, in <module>
    main()
  File "C:\Users\mikeo85\.cask\bin\cask", line 387, in main
    if ENVB.get(b'TRAVIS', b'') == b'true':
  File "C:\Program Files (x86)\Python36-32\lib\_collections_abc.py", line 660, in get
    return self[key]
  File "C:\Program Files (x86)\Python36-32\lib\os.py", line 666, in __getitem__
    value = self._data[self.encodekey(key)]
  File "C:\Program Files (x86)\Python36-32\lib\os.py", line 735, in encodekey
    return encode(key).upper()
  File "C:\Program Files (x86)\Python36-32\lib\os.py", line 730, in check_str
    raise TypeError("str expected, not %s" % type(value).__name__)
TypeError: str expected, not bytes
[31mCask could not be bootstrapped. Try again later, or report an issue at https://github.com/cask/cask/issues[0m

C:\Users\mikeo85>python --version
Python 3.6.5
```

**Comment by bradyt** [comment]
From https://github.com/cask/cask/issues/285#issuecomment-89366147.

> @melihovv the workaround is to run it with Python 2.

@mikeo85, let us know if the above helps?

**Comment by mikeo85** [comment]
Bingo, Python 2 works -- thank you.

**Comment by conao3** [comment]
The issue solved? close.
